version: "3.1"
services:
  muscu-app-db:
    container_name: muscu-app-db
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - muscu-network
  muscu-app-adminer:
    container_name: muscu-app-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8081
networks:
  muscu-network:
volumes:
  postgres-data: